<?php
	include('./templates/head.template.php');
	include('./templates/header.template.php');
	include(include_template($template_left));
	include(include_template($template_main));
	include('./templates/admin_panel.template.php');
	include('./templates/prod.template.php');
	include('./templates/footer.template.php');
?>